name: Bump tools version

on:
  schedule:
  - cron: "0 8 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run bumper.sh
      run: $(git rev-parse --show-toplevel)/hacks/bumper.sh

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        title: "Automatic versions update"
        assignees: "rrey"
        base: "master"
