name: Release

on:
  release:
    types: [published]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag rrey/terraform-runner:$(git tag --points-at HEAD)

    - name: Push the image
      run: |
          docker login -u rrey -p $DOCKERHUB_TOKEN
          docker push rrey/terraform-runner:$(git tag --points-at HEAD)
      env:
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}


  azdo-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build . --build-arg BASE_IMG=rrey/azdo-base-container:v0.1.2 --file Dockerfile --tag rrey/terraform-runner:$(git tag --points-at HEAD)-azdo

    - name: Push the image
      run: |
          docker login -u rrey -p $DOCKERHUB_TOKEN
          docker push rrey/terraform-runner:$(git tag --points-at HEAD)
      env:
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
